#!/usr/bin/env python3

import re
import requests


level = str(0)
username = f"natas{level}"
passwd = "natas0"
url = f"http://natas{level}.natas.labs.overthewire.org"
response = requests.get(url, auth=(username, passwd))
content = response.text
print(content)
next_passwd = re.findall('<!--The password for natas1 is (.*) -->', content)
print(next_passwd[0])
