#!/usr/bin/env python3


import re
import requests

level = str(8)
usr = f"natas{level}"
passwd = "DBfUBfqQG69KvJvJ1iAbMoIpwSNQ9bWe"
#url = f"http://natas{level}.natas.labs.overthewire.org/index-source.html"

url = f"http://natas{level}.natas.labs.overthewire.org/"
response = requests.post(url, auth=(usr, passwd), data={"secret":"oubWYf2kBq", "submit" : "submit"})
#response = requests.get(url, auth=(usr, passwd))
content = response.text
print(content)
next_pass = re.findall("natas9 is (.*)", content)[0]
print(next_pass)
